name: Continuous integration/deployment

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: ['10.x', '12.x', '14.x',  '16.x']
    timeout-minutes: 5
    runs-on:  ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm test